# Generated by Django 4.2.11 on 2024-03-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_carrt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paynow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_card', models.CharField(max_length=50)),
                ('number_card', models.IntegerField()),
                ('date_card', models.CharField(max_length=50)),
                ('cvv_card', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
